// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CarCreateSchema = {
    properties: {
        model: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Model'
        },
        wav: {
            type: 'integer',
            title: 'Wav',
            default: 0
        },
        marker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Marker',
            default: 'premium'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        year: {
            type: 'integer',
            title: 'Year'
        },
        vin_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Number'
        },
        plate_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plate Number'
        },
        state: {
            type: 'string',
            maxLength: 2,
            title: 'State',
            default: 'NY'
        },
        registration_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Expires At'
        },
        insurance_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expires At'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        installation_fee_for_safety_equipment: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Fee For Safety Equipment'
        },
        insurance_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expenses'
        },
        service_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Expenses'
        },
        maintenance_costs: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maintenance Costs'
        },
        full_coverage_auto_insurance: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Coverage Auto Insurance'
        },
        other_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Other Expenses'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'available'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['model', 'year'],
    title: 'CarCreate'
} as const;

export const CarPublicSchema = {
    properties: {
        model: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Model'
        },
        wav: {
            type: 'integer',
            title: 'Wav',
            default: 0
        },
        marker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Marker',
            default: 'premium'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        year: {
            type: 'integer',
            title: 'Year'
        },
        vin_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Number'
        },
        plate_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plate Number'
        },
        state: {
            type: 'string',
            maxLength: 2,
            title: 'State',
            default: 'NY'
        },
        registration_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Expires At'
        },
        insurance_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expires At'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        installation_fee_for_safety_equipment: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Fee For Safety Equipment'
        },
        insurance_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expenses'
        },
        service_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Expenses'
        },
        maintenance_costs: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maintenance Costs'
        },
        full_coverage_auto_insurance: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Coverage Auto Insurance'
        },
        other_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Other Expenses'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'available'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['model', 'year', 'id'],
    title: 'CarPublic'
} as const;

export const CarUpdateSchema = {
    properties: {
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        wav: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wav'
        },
        marker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Marker'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        vin_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Number'
        },
        plate_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plate Number'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        registration_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Expires At'
        },
        insurance_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expires At'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        installation_fee_for_safety_equipment: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Fee For Safety Equipment'
        },
        insurance_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Expenses'
        },
        service_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Expenses'
        },
        maintenance_costs: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maintenance Costs'
        },
        full_coverage_auto_insurance: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Coverage Auto Insurance'
        },
        other_expenses: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Other Expenses'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CarUpdate'
} as const;

export const CarsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CarPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CarsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LicensePlateCreateSchema = {
    properties: {
        plate_number: {
            type: 'string',
            maxLength: 16,
            minLength: 2,
            title: 'Plate Number'
        },
        plate_state: {
            type: 'string',
            maxLength: 2,
            title: 'Plate State',
            default: 'NY'
        },
        purchase_date: {
            type: 'string',
            format: 'date',
            title: 'Purchase Date'
        },
        purchase_amount: {
            type: 'number',
            title: 'Purchase Amount'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'available'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['plate_number', 'purchase_date', 'purchase_amount'],
    title: 'LicensePlateCreate'
} as const;

export const LicensePlatePublicSchema = {
    properties: {
        plate_number: {
            type: 'string',
            maxLength: 16,
            minLength: 2,
            title: 'Plate Number'
        },
        plate_state: {
            type: 'string',
            maxLength: 2,
            title: 'Plate State',
            default: 'NY'
        },
        purchase_date: {
            type: 'string',
            format: 'date',
            title: 'Purchase Date'
        },
        purchase_amount: {
            type: 'number',
            title: 'Purchase Amount'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'available'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['plate_number', 'purchase_date', 'purchase_amount', 'id'],
    title: 'LicensePlatePublic'
} as const;

export const LicensePlateUpdateSchema = {
    properties: {
        plate_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plate Number'
        },
        plate_state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plate State'
        },
        purchase_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Date'
        },
        purchase_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Amount'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'LicensePlateUpdate'
} as const;

export const LicensePlatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LicensePlatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LicensePlatesPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlateLeaseCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        rent_amount: {
            type: 'number',
            title: 'Rent Amount'
        },
        frequency: {
            type: 'string',
            maxLength: 16,
            title: 'Frequency',
            default: 'monthly'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'active'
        },
        plate_id: {
            type: 'string',
            format: 'uuid',
            title: 'Plate Id'
        },
        renter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Renter Id'
        }
    },
    type: 'object',
    required: ['start_date', 'rent_amount', 'plate_id', 'renter_id'],
    title: 'PlateLeaseCreate'
} as const;

export const PlateLeasePublicSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        rent_amount: {
            type: 'number',
            title: 'Rent Amount'
        },
        frequency: {
            type: 'string',
            maxLength: 16,
            title: 'Frequency',
            default: 'monthly'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'active'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        plate_id: {
            type: 'string',
            format: 'uuid',
            title: 'Plate Id'
        },
        renter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Renter Id'
        }
    },
    type: 'object',
    required: ['start_date', 'rent_amount', 'id', 'plate_id', 'renter_id'],
    title: 'PlateLeasePublic'
} as const;

export const PlateLeaseUpdateSchema = {
    properties: {
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        rent_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rent Amount'
        },
        frequency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frequency'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'PlateLeaseUpdate'
} as const;

export const PlateLeasesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlateLeasePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlateLeasesPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RenterCreateSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Full Name'
        },
        phone: {
            type: 'string',
            maxLength: 20,
            minLength: 7,
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        driver_license_number: {
            type: 'string',
            maxLength: 64,
            minLength: 4,
            title: 'Driver License Number'
        },
        driver_license_state: {
            type: 'string',
            maxLength: 2,
            title: 'Driver License State',
            default: 'NY'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        }
    },
    type: 'object',
    required: ['full_name', 'phone', 'driver_license_number'],
    title: 'RenterCreate'
} as const;

export const RenterPublicSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Full Name'
        },
        phone: {
            type: 'string',
            maxLength: 20,
            minLength: 7,
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        driver_license_number: {
            type: 'string',
            maxLength: 64,
            minLength: 4,
            title: 'Driver License Number'
        },
        driver_license_state: {
            type: 'string',
            maxLength: 2,
            title: 'Driver License State',
            default: 'NY'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['full_name', 'phone', 'driver_license_number', 'id'],
    title: 'RenterPublic'
} as const;

export const RenterUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        driver_license_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Driver License Number'
        },
        driver_license_state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Driver License State'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        }
    },
    type: 'object',
    title: 'RenterUpdate'
} as const;

export const RentersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RenterPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RentersPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;