// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CarCreate = {
    model: string;
    wav?: number;
    marker?: (string | null);
    color?: (string | null);
    year: number;
    vin_number?: (string | null);
    plate_number?: (string | null);
    state?: string;
    registration_expires_at?: (string | null);
    insurance_expires_at?: (string | null);
    price?: (number | null);
    installation_fee_for_safety_equipment?: (number | null);
    insurance_expenses?: (number | null);
    service_expenses?: (number | null);
    maintenance_costs?: (number | null);
    full_coverage_auto_insurance?: (number | null);
    other_expenses?: (number | null);
    status?: string;
    notes?: (string | null);
};

export type CarPublic = {
    model: string;
    wav?: number;
    marker?: (string | null);
    color?: (string | null);
    year: number;
    vin_number?: (string | null);
    plate_number?: (string | null);
    state?: string;
    registration_expires_at?: (string | null);
    insurance_expires_at?: (string | null);
    price?: (number | null);
    installation_fee_for_safety_equipment?: (number | null);
    insurance_expenses?: (number | null);
    service_expenses?: (number | null);
    maintenance_costs?: (number | null);
    full_coverage_auto_insurance?: (number | null);
    other_expenses?: (number | null);
    status?: string;
    notes?: (string | null);
    id: string;
};

export type CarsPublic = {
    data: Array<CarPublic>;
    count: number;
};

export type CarUpdate = {
    model?: (string | null);
    wav?: (number | null);
    marker?: (string | null);
    color?: (string | null);
    year?: (number | null);
    vin_number?: (string | null);
    plate_number?: (string | null);
    state?: (string | null);
    registration_expires_at?: (string | null);
    insurance_expires_at?: (string | null);
    price?: (number | null);
    installation_fee_for_safety_equipment?: (number | null);
    insurance_expenses?: (number | null);
    service_expenses?: (number | null);
    maintenance_costs?: (number | null);
    full_coverage_auto_insurance?: (number | null);
    other_expenses?: (number | null);
    status?: (string | null);
    notes?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LicensePlateCreate = {
    plate_number: string;
    plate_state?: string;
    purchase_date: string;
    purchase_amount: number;
    status?: string;
    notes?: (string | null);
};

export type LicensePlatePublic = {
    plate_number: string;
    plate_state?: string;
    purchase_date: string;
    purchase_amount: number;
    status?: string;
    notes?: (string | null);
    id: string;
};

export type LicensePlatesPublic = {
    data: Array<LicensePlatePublic>;
    count: number;
};

export type LicensePlateUpdate = {
    plate_number?: (string | null);
    plate_state?: (string | null);
    purchase_date?: (string | null);
    purchase_amount?: (number | null);
    status?: (string | null);
    notes?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PlateLeaseCreate = {
    start_date: string;
    end_date?: (string | null);
    rent_amount: number;
    frequency?: string;
    status?: string;
    plate_id: string;
    renter_id: string;
};

export type PlateLeasePublic = {
    start_date: string;
    end_date?: (string | null);
    rent_amount: number;
    frequency?: string;
    status?: string;
    id: string;
    plate_id: string;
    renter_id: string;
};

export type PlateLeasesPublic = {
    data: Array<PlateLeasePublic>;
    count: number;
};

export type PlateLeaseUpdate = {
    start_date?: (string | null);
    end_date?: (string | null);
    rent_amount?: (number | null);
    frequency?: (string | null);
    status?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RenterCreate = {
    full_name: string;
    phone: string;
    email?: (string | null);
    driver_license_number: string;
    driver_license_state?: string;
    address?: (string | null);
};

export type RenterPublic = {
    full_name: string;
    phone: string;
    email?: (string | null);
    driver_license_number: string;
    driver_license_state?: string;
    address?: (string | null);
    id: string;
};

export type RentersPublic = {
    data: Array<RenterPublic>;
    count: number;
};

export type RenterUpdate = {
    full_name?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    driver_license_number?: (string | null);
    driver_license_state?: (string | null);
    address?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CarsReadCarsData = {
    limit?: number;
    model?: (string | null);
    plateNumber?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type CarsReadCarsResponse = (CarsPublic);

export type CarsCreateCarData = {
    requestBody: CarCreate;
};

export type CarsCreateCarResponse = (CarPublic);

export type CarsReadCarData = {
    id: string;
};

export type CarsReadCarResponse = (CarPublic);

export type CarsUpdateCarData = {
    id: string;
    requestBody: CarUpdate;
};

export type CarsUpdateCarResponse = (CarPublic);

export type CarsDeleteCarData = {
    id: string;
};

export type CarsDeleteCarResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LeasesReadLeasesData = {
    limit?: number;
    plateNumber?: (string | null);
    renterName?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type LeasesReadLeasesResponse = (PlateLeasesPublic);

export type LeasesCreateLeaseData = {
    requestBody: PlateLeaseCreate;
};

export type LeasesCreateLeaseResponse = (PlateLeasePublic);

export type LeasesReadLeaseData = {
    id: string;
};

export type LeasesReadLeaseResponse = (PlateLeasePublic);

export type LeasesUpdateLeaseData = {
    id: string;
    requestBody: PlateLeaseUpdate;
};

export type LeasesUpdateLeaseResponse = (PlateLeasePublic);

export type LeasesDeleteLeaseData = {
    id: string;
};

export type LeasesDeleteLeaseResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlatesReadPlatesData = {
    limit?: number;
    plateNumber?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type PlatesReadPlatesResponse = (LicensePlatesPublic);

export type PlatesCreateLicensePlateData = {
    requestBody: LicensePlateCreate;
};

export type PlatesCreateLicensePlateResponse = (LicensePlatePublic);

export type PlatesReadPlateData = {
    id: string;
};

export type PlatesReadPlateResponse = (LicensePlatePublic);

export type PlatesUpdateLicensePlateData = {
    id: string;
    requestBody: LicensePlateUpdate;
};

export type PlatesUpdateLicensePlateResponse = (LicensePlatePublic);

export type PlatesDeleteLicensePlateData = {
    id: string;
};

export type PlatesDeleteLicensePlateResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RentersReadRentersData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type RentersReadRentersResponse = (RentersPublic);

export type RentersCreateRenterData = {
    requestBody: RenterCreate;
};

export type RentersCreateRenterResponse = (RenterPublic);

export type RentersReadRenterData = {
    id: string;
};

export type RentersReadRenterResponse = (RenterPublic);

export type RentersUpdateRenterData = {
    id: string;
    requestBody: RenterUpdate;
};

export type RentersUpdateRenterResponse = (RenterPublic);

export type RentersDeleteRenterData = {
    id: string;
};

export type RentersDeleteRenterResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);