"""Add RentalPayment model

Revision ID: 13f9198d8b4b
Revises: d623e2b78e43
Create Date: 2026-01-14 22:16:05.102723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.models


# revision identifiers, used by Alembic.
revision = '13f9198d8b4b'
down_revision = 'd623e2b78e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentalpayment',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('rental_id', app.models.UUID(), nullable=False),
    sa.Column('create_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['carrental.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentalpayment')
    # ### end Alembic commands ###
