"""Update PlateLease model

Revision ID: 3b20e77ad373
Revises: e80b4a0f4186
Create Date: 2026-01-15 19:21:02.794954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b20e77ad373'
down_revision = 'e80b4a0f4186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platelease', sa.Column('total_amount', sa.Float(), nullable=False, server_default="0.0"))
    op.add_column('platelease', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False, server_default="unpaid"))
    op.add_column('platelease', sa.Column('paid_amount', sa.Float(), nullable=False, server_default="0.0"))
    op.add_column('platelease', sa.Column('remaining_amount', sa.Float(), nullable=False, server_default="0.0"))
    op.add_column('platelease', sa.Column('rental_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default="lease"))
    op.add_column('platelease', sa.Column('create_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('platelease', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('platelease', sa.Column('update_time', sa.DateTime(), nullable=True))
    with op.batch_alter_table('platelease') as batch_op:
        batch_op.drop_column('rent_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platelease', sa.Column('rent_amount', sa.FLOAT(), nullable=False))
    op.drop_column('platelease', 'update_time')
    op.drop_column('platelease', 'create_time')
    op.drop_column('platelease', 'create_by')
    op.drop_column('platelease', 'rental_type')
    op.drop_column('platelease', 'remaining_amount')
    op.drop_column('platelease', 'paid_amount')
    op.drop_column('platelease', 'payment_status')
    op.drop_column('platelease', 'total_amount')
    # ### end Alembic commands ###
