"""Make car_id nullable in Python model to allow autoincrement

Revision ID: 6957df018a1b
Revises: 4af6f1c12c5b
Create Date: 2026-01-13 20:03:16.569555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6957df018a1b'
down_revision = '4af6f1c12c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
