"""Add cars table

Revision ID: c12e48605b0a
Revises: 1a31ce608336
Create Date: 2026-01-13 18:49:24.536273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.models


# revision identifiers, used by Alembic.
revision = 'c12e48605b0a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('wav', sa.Integer(), nullable=False),
    sa.Column('marker', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('plate_number', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('registration_expires_at', sa.DateTime(), nullable=True),
    sa.Column('insurance_expires_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('installation_fee_for_safety_equipment', sa.Float(), nullable=True),
    sa.Column('insurance_expenses', sa.Float(), nullable=True),
    sa.Column('service_expenses', sa.Float(), nullable=True),
    sa.Column('maintenance_costs', sa.Float(), nullable=True),
    sa.Column('full_coverage_auto_insurance', sa.Float(), nullable=True),
    sa.Column('other_expenses', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
