"""Update CarRental model with total_amount and payments

Revision ID: d623e2b78e43
Revises: 5fd1f354473f
Create Date: 2026-01-14 21:54:11.333114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd623e2b78e43'
down_revision = '5fd1f354473f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrental', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('carrental', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    op.add_column('carrental', sa.Column('paid_amount', sa.Float(), nullable=False))
    op.add_column('carrental', sa.Column('create_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('carrental', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('carrental', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_column('carrental', 'rent_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrental', sa.Column('rent_amount', sa.FLOAT(), nullable=False))
    op.drop_column('carrental', 'update_time')
    op.drop_column('carrental', 'create_time')
    op.drop_column('carrental', 'create_by')
    op.drop_column('carrental', 'paid_amount')
    op.drop_column('carrental', 'payment_status')
    op.drop_column('carrental', 'total_amount')
    # ### end Alembic commands ###
