"""Add rental_type to CarRental

Revision ID: e80b4a0f4186
Revises: eed4773f6992
Create Date: 2026-01-15 17:51:47.312118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e80b4a0f4186'
down_revision = 'eed4773f6992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrental', sa.Column('rental_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default="lease"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrental', 'rental_type')
    # ### end Alembic commands ###
