"""Add CarRental model

Revision ID: ee90ea4725d6
Revises: f0dd27167b80
Create Date: 2026-01-14 20:25:33.855613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.models


# revision identifiers, used by Alembic.
revision = 'ee90ea4725d6'
down_revision = 'f0dd27167b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrental',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('car_id', app.models.UUID(), nullable=False),
    sa.Column('renter_id', app.models.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_id'], ['renter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrental')
    # ### end Alembic commands ###
