"""Add remaining_amount to CarRental

Revision ID: eed4773f6992
Revises: 13f9198d8b4b
Create Date: 2026-01-14 22:29:51.593967

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eed4773f6992'
down_revision = '13f9198d8b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrental', sa.Column('remaining_amount', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrental', 'remaining_amount')
    # ### end Alembic commands ###
