"""Add create_by create_time update_time to Car

Revision ID: f0dd27167b80
Revises: 6957df018a1b
Create Date: 2026-01-13 20:20:10.214268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f0dd27167b80'
down_revision = '6957df018a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('create_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('car', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('car', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'update_time')
    op.drop_column('car', 'create_time')
    op.drop_column('car', 'create_by')
    # ### end Alembic commands ###
